### ISSUE TITLE
[Bug]: kotlinx.datetime binary incompatibility

### ISSUE THREAD

**Issue by bakjoul** [alexzhirkevich/compottie#47]
### What happened?

Hi,
When using kotlinx-datetime 0.7.0, i don't know why my animations don't show anymore.
If i rollback to 0.6.8, they work again.
Am i the only one having this issue?

### What Compottie version do you experience the bug on?

2.0.0-rc04

### What platforms are you seeing the problem on?

Android

### Does Compottie log anythyng to the stdout / your logger set with `Compottie.logger`?

```shell

```

**Comment by alexzhirkevich** [comment]
The issue was fixed in [kotlinx-datetime 0.7.1](https://github.com/Kotlin/kotlinx-datetime/releases/tag/v0.7.1)

**Comment by cvicart-dev** [comment]
`kotlinx-datetime 0.7.1` does not fix the issue.
My animations still don't show up, and when compiling the app using Proguard, it complains about missing class: `kotlinx.datetime.Clock`

Please update the dependency to `0.7.1` or use the stable internal `kotlin.time.Clock` Kotlin class

<img width="1498" height="221" alt="Image" src="https://github.com/user-attachments/assets/c8ecb7cf-8e2b-46de-a5f8-b97898d16f85" />
